# Node configuration
node:
  # Unique identifier for this node (leave empty for auto-generation)
  id: ""
  
  # Traceroute settings
  traceroute:
    max_hops: 30  # Reduced for faster results
    timeout: 2  # seconds per hop
    interval: 300  # seconds between traceroute rounds (5 minutes)
    auto_map_own_subnet: true  # Automatically map subnet of external IP
    subnet_size: 28  # Subnet size to map (8-30): /28=14 IPs for faster testing
    verify_reachable: true  # Ping targets before traceroute to avoid timeouts
  
  # Well-known targets to always include in mapping
  well_known_targets:
    # Public DNS servers
    - "8.8.8.8"        # Google DNS
    - "8.8.4.4"        # Google DNS Secondary
    - "1.1.1.1"        # Cloudflare DNS
    - "1.0.0.1"        # Cloudflare DNS Secondary
    - "9.9.9.9"        # Quad9 DNS
    - "208.67.222.222" # OpenDNS
    - "208.67.220.220" # OpenDNS Secondary
    # Root DNS servers (selection)
    - "198.41.0.4"     # a.root-servers.net
    - "199.9.14.201"   # b.root-servers.net
    - "192.33.4.12"    # c.root-servers.net
    # Major CDN/Cloud endpoints
    - "13.107.42.14"   # Microsoft Azure
    - "104.16.132.229" # Cloudflare
    - "151.101.1.140"  # Fastly
  
  # Mobility settings for devices that change location/IP
  mobility:
    cleanup_old_location: false  # Keep historical data (set true to clean up old subnet data)
    detect_interval: 60  # seconds between IP change checks (default heartbeat)
    
  # Rate limiting disabled for comprehensive mapping
  rate_limit:
    max_traceroutes_per_hour: 0  # 0 = unlimited
    max_concurrent_traceroutes: 10  # Allow more concurrent traces
    enable_rate_limiting: false  # Disable rate limiting

# IPFS configuration
ipfs:
  # IPFS API multiaddr
  api_address: "/ip4/127.0.0.1/tcp/5001"
  
  # PubSub channels
  channels:
    discovery: "intermap-discovery"
    topology: "intermap-topology"
    verification: "intermap-verification"  # For dead IP verification requests
  
  # Publish interval for topology data
  publish_interval: 600  # seconds (10 minutes)

# Graph configuration
graph:
  # Output directory for GEXF files
  output_dir: "./output"
  
  # Graph metadata
  title: "Distributed Internet Topology Map"
  description: "Collaborative network topology mapping"

# Bandwidth testing configuration
bandwidth:
  # Enable automatic bandwidth testing
  enabled: true
  
  # iperf3 settings
  iperf3:
    enabled: true
    port: 5201  # Default iperf3 port
    duration: 10  # seconds per test
    interval: 7200  # seconds between tests (2 hours)
    parallel_streams: 1
    sequential_only: true  # Only run one test at a time (avoid congestion)
    
    # Public iperf3 servers to test against
    public_servers:
      - host: "ping.online.net"
        port: 5201
        location: "France"
      - host: "iperf.he.net"
        port: 5201
        location: "USA"
      - host: "speedtest.serverius.net"
        port: 5002
        location: "Netherlands"
  
  # Bandwidth test settings
  test_all_discovered_ips: true  # Probe all IPs for iperf3 support
  test_intermap_nodes: true  # Always test to other Intermap nodes
  use_peak_results: true  # Use peak bandwidth for edge coloring (not average)
  
  # speedtest-cli settings (fallback)
  speedtest:
    enabled: true
    interval: 14400  # seconds between tests (4 hours)
  
  # Bandwidth test rate limiting
  rate_limit:
    max_tests_per_hour: 20  # Increased for comprehensive testing
    sequential_only: true  # One test at a time

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "topology_node.log"
  max_size_mb: 10
  backup_count: 3
