# Node configuration
node:
  # Unique identifier for this node (leave empty for auto-generation)
  id: ""
  
  # Traceroute settings
  traceroute:
    max_hops: 30  # Reduced for faster results
    timeout: 2  # seconds per hop
    interval: 300  # seconds between traceroute rounds (5 minutes)
    auto_map_own_subnet: true  # Automatically map subnet of external IP
    subnet_size: 28  # Subnet size to map (8-30): /28=14 IPs for faster testing
    verify_reachable: true  # Ping targets before traceroute to avoid timeouts
  
  # Well-known targets to always include in mapping
  well_known_targets:
    # Public DNS servers
    - "8.8.8.8"        # Google DNS
    - "8.8.4.4"        # Google DNS Secondary
    - "1.1.1.1"        # Cloudflare DNS
    - "1.0.0.1"        # Cloudflare DNS Secondary
    - "9.9.9.9"        # Quad9 DNS
    - "208.67.222.222" # OpenDNS
    - "208.67.220.220" # OpenDNS Secondary
    # Root DNS servers (selection)
    - "198.41.0.4"     # a.root-servers.net
    - "199.9.14.201"   # b.root-servers.net
    - "192.33.4.12"    # c.root-servers.net
    # Major CDN/Cloud endpoints
    - "13.107.42.14"   # Microsoft Azure
    - "104.16.132.229" # Cloudflare
    - "151.101.1.140"  # Fastly
    # Public iperf3 servers (geographically diverse)
    - "ping.online.net"           # France (Paris) - 100Gbps
    - "iperf.he.net"              # USA (Hurricane Electric)
    - "speedtest.wtnet.de"        # Germany (40Gbps)
    - "speedtest.serverius.net"   # Netherlands
    - "speedtest.lon12.uk.leaseweb.net"  # UK (London) - 10Gbps
    - "speedtest.syd12.au.leaseweb.net"  # Australia (Sydney) - 10Gbps
    - "speedtest.tyo11.jp.leaseweb.net"  # Japan (Tokyo) - 10Gbps
    - "speedtest.dal13.us.leaseweb.net"  # USA (Dallas) - 10Gbps
    - "speedtest.fra1.de.leaseweb.net"   # Germany (Frankfurt) - 10Gbps
    - "speedtest.ams1.nl.leaseweb.net"   # Netherlands (Amsterdam) - 10Gbps
  
  # Mobility settings for devices that change location/IP
  mobility:
    cleanup_old_location: false  # Keep historical data (set true to clean up old subnet data)
    detect_interval: 60  # seconds between IP change checks (default heartbeat)
    
  # Rate limiting disabled for comprehensive mapping
  rate_limit:
    max_traceroutes_per_hour: 0  # 0 = unlimited
    max_concurrent_traceroutes: 10  # Allow more concurrent traces
    enable_rate_limiting: false  # Disable rate limiting

# IPFS configuration
ipfs:
  # IPFS API multiaddr
  api_address: "/ip4/127.0.0.1/tcp/5001"
  
  # PubSub channels
  channels:
    discovery: "intermap-discovery"
    topology: "intermap-topology"
    verification: "intermap-verification"  # For dead IP verification requests
  
  # Publish interval for topology data
  publish_interval: 600  # seconds (10 minutes)

# Graph configuration
graph:
  # Output directory for GEXF files
  output_dir: "./output"
  
  # Graph metadata
  title: "Distributed Internet Topology Map"
  description: "Collaborative network topology mapping"

# Bandwidth testing configuration
bandwidth:
  # Enable automatic bandwidth testing
  enabled: true
  
  # Test ALL discovered IPs (every hop from traceroutes)
  test_discovered_hops: true
  test_intermap_nodes: true  # Always test to other Intermap nodes
  
  # iperf3 settings
  iperf3:
    enabled: true
    duration: 5  # seconds per test (reduced for faster comprehensive testing)
    parallel_streams: 1  # Single stream for more accurate RTT correlation
    reverse_mode: false  # Download test (false = upload)
    
    # Well-known public iperf3 servers with open ports
    public_servers:
      # Europe
      - host: "ping.online.net"
        port: 5201
        location: "France"
      - host: "speedtest.wtnet.de"
        port: 5201
        location: "Germany"
      - host: "speedtest.lon12.uk.leaseweb.net"
        port: 5201
        location: "UK"
      - host: "speedtest.ams1.nl.leaseweb.net"
        port: 5201
        location: "Netherlands"
      # Americas
      - host: "speedtest.dal13.us.leaseweb.net"
        port: 5201
        location: "USA-Dallas"
      - host: "speedtest.nyc1.us.leaseweb.net"
        port: 5201
        location: "USA-NewYork"
      # Asia-Pacific
      - host: "speedtest.tyo11.jp.leaseweb.net"
        port: 5201
        location: "Japan"
      - host: "speedtest.syd12.au.leaseweb.net"
        port: 5201
        location: "Australia"
    
    # Auto-discovery settings
    auto_discover_servers: true  # Try port 5201 on all discovered IPs
    discovery_timeout: 2  # seconds to wait for iperf3 server response
    max_concurrent_tests: 3  # Limit concurrent bandwidth tests
    test_interval: 300  # seconds between bandwidth test rounds (5 minutes)
  
  # Bandwidth test rate limiting
  rate_limit:
    max_tests_per_hour: 100  # Allow many tests for comprehensive mapping
    sequential_only: false  # Allow concurrent tests (up to max_concurrent_tests)
  
  # Store results in graph edges
  store_in_graph: true
  use_peak_results: true  # Use peak bandwidth, not average

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "topology_node.log"
  max_size_mb: 10
  backup_count: 3

